#!/usr/bin/env -S sh -c 'if command -v nix-shell > /dev/null; then exec nix-shell "$0"; else exec sh "$0"; fi'
#!nix-shell -i dash -p coreutils dash cowsay lolcat

#         DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#                     Version 2, December 2004
#
#  Copyright (C) 2004 Sam Hocevar <sam@hocevar.net>
#
#  Everyone is permitted to copy and distribute verbatim or modified
#  copies of this license document, and changing it is allowed as long
#  as the name is changed.
#
#             DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#    TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
#
#   0. You just DO WHAT THE FUCK YOU WANT TO.

# dependencies:
# - sh (bash, dash, e.t.c)
# - either nix or cowsay and lolcat

uname -a | cowsay -f tux | lolcat
